# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol/protocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protocol/protocol.proto\"\x13\n\x05Hello\x12\n\n\x02id\x18\x01 \x01(\t\"\x1e\n\x03\x42ye\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\",\n\rPlayerMessage\x12\x1b\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x0b.ActionType\"0\n\x0cPlayerUpdate\x12\n\n\x02id\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\r\x12\t\n\x01y\x18\x03 \x01(\r\"N\n\tMapUpdate\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x05 \x03(\r\"\x9c\x01\n\rServerMessage\x12#\n\x07\x63urrent\x18\x01 \x01(\x0b\x32\r.PlayerUpdateH\x00\x88\x01\x01\x12&\n\x0fplayers_updates\x18\x02 \x03(\x0b\x32\r.PlayerUpdate\x12#\n\nmap_update\x18\x03 \x01(\x0b\x32\n.MapUpdateH\x01\x88\x01\x01\x42\n\n\x08_currentB\r\n\x0b_map_update*1\n\x06Status\x12\x06\n\x02Ok\x10\x00\x12\t\n\x05\x45rror\x10\x01\x12\x14\n\x10\x41lreadyConnected\x10\x02*\xe1\x01\n\nActionType\x12\x0e\n\nDisconnect\x10\x00\x12\n\n\x06MoveUp\x10\x01\x12\x0c\n\x08MoveDown\x10\x02\x12\r\n\tMoveRight\x10\x03\x12\x0c\n\x08MoveLeft\x10\x04\x12\x0e\n\nHalfDashUp\x10\x05\x12\x0e\n\nFullDashUp\x10\x06\x12\x10\n\x0cHalfDashDown\x10\x07\x12\x10\n\x0c\x46ullDashDown\x10\x08\x12\x10\n\x0cHalfDashLeft\x10\t\x12\x10\n\x0c\x46ullDashLeft\x10\n\x12\x11\n\rHalfDashRight\x10\x0b\x12\x11\n\rFullDashRight\x10\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol.protocol_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=415
  _STATUS._serialized_end=464
  _ACTIONTYPE._serialized_start=467
  _ACTIONTYPE._serialized_end=692
  _HELLO._serialized_start=27
  _HELLO._serialized_end=46
  _BYE._serialized_start=48
  _BYE._serialized_end=78
  _PLAYERMESSAGE._serialized_start=80
  _PLAYERMESSAGE._serialized_end=124
  _PLAYERUPDATE._serialized_start=126
  _PLAYERUPDATE._serialized_end=174
  _MAPUPDATE._serialized_start=176
  _MAPUPDATE._serialized_end=254
  _SERVERMESSAGE._serialized_start=257
  _SERVERMESSAGE._serialized_end=413
# @@protoc_insertion_point(module_scope)
