# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotocol.proto\"\x13\n\x05Hello\x12\n\n\x02id\x18\x01 \x01(\t\"\x1e\n\x03\x42ye\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\"7\n\x0eMovementAction\x12%\n\tdirection\x18\x01 \x01(\x0e\x32\x12.MovementDirection\"f\n\x06\x41\x63tion\x12\x19\n\x04type\x18\x01 \x01(\x0e\x32\x0b.ActionType\x12-\n\x0fmovement_action\x18\x02 \x01(\x0b\x32\x0f.MovementActionH\x00\x88\x01\x01\x42\x12\n\x10_movement_action*\x1b\n\x06Status\x12\x06\n\x02Ok\x10\x00\x12\t\n\x05\x45rror\x10\x01*:\n\x11MovementDirection\x12\x06\n\x02Up\x10\x00\x12\x08\n\x04\x44own\x10\x01\x12\x08\n\x04Left\x10\x02\x12\t\n\x05Right\x10\x03*9\n\nActionType\x12\x0c\n\x08Movement\x10\x00\x12\x0e\n\nDisconnect\x10\x01\x12\r\n\tKeepAlive\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=232
  _STATUS._serialized_end=259
  _MOVEMENTDIRECTION._serialized_start=261
  _MOVEMENTDIRECTION._serialized_end=319
  _ACTIONTYPE._serialized_start=321
  _ACTIONTYPE._serialized_end=378
  _HELLO._serialized_start=18
  _HELLO._serialized_end=37
  _BYE._serialized_start=39
  _BYE._serialized_end=69
  _MOVEMENTACTION._serialized_start=71
  _MOVEMENTACTION._serialized_end=126
  _ACTION._serialized_start=128
  _ACTION._serialized_end=230
# @@protoc_insertion_point(module_scope)
